### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by travellingprog** [appier/graphql-cookbook#1]
Could you please add a license for this repo?

I want to a lot of this code to do integration tests for a GraphQL client I'm building. I like that this GraphQL API has mutations and doesn't have any database dependencies!

Thanks in advance

**Comment by mofas** [comment]
Hi travellingprog:

Thanks for your suggestion. Already Done in https://github.com/appier/graphql-cookbook/commit/612c423d0dbaf62b101c1ef6f99b0f5e72f9e165

**Comment by travellingprog** [comment]
Thanks @mofas !
